FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy the application's code
COPY package*.json ./

# install angular cli in the image
RUN npm install -g @angular/cli

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Expose the port the application runs on
EXPOSE 4200

# Serve the application
CMD ["npm", "start"]